services:
  frontend:
    container_name: frontend
    image: dmcleansait/studentfrontend:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
  backend:
    container_name: backend
    image: dmcleansait/studentrestfulapi:latest
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://davonte:password@studentdb:5432/StudentDB?schema=public
  db:
    container_name: studentdb
    image: postgres:15
    environment:
      POSTGRES_USER: davonte
      POSTGRES_PASSWORD: password
      POSTGRES_DB: StudentDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
